version: 2

jobs:
  fetch-code:
    docker:
      - image: circleci/node:8.11.2-browsers
    steps:
      - checkout
      - persist_to_workspace:
          paths:
            -

  firebase:
    docker:
      - image: circleci/node:8.11.2-browsers
    working_directory: ~/firebase
    steps:
      - attach_workspace
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Firebase cli install
          command: npm install --save-dev firebase-tools
      - run:
          name: Firebase functions deploy
          command: ./node_modules/.bin/firebase deploy --only functions --token "$FIREBASE_TOKEN"
      - run:
          name: Firebase hosting deploy
          command: ./node_modules/.bin/firebase deploy --only hosting --token "$FIREBASE_TOKEN"

  react-app-admin:
    docker:
      - image: circleci/node:8.11.2-browsers
    working_directory: ~/admin
    steps:
      - attach_workspace
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build

  react-app-web:
    docker:
      - image: circleci/node:8.11.2-browsers
    working_directory: ~/web
    steps:
      - attach_workspace
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - fetch-code
      - react-app-admin:
          requires:
            - fetch-code
      - react-app-web:
          requires:
            - fetch-code
      - firebase:
          requires:
            - react-app-admin
            - react-app-web
          filters:
            branches:
              only:
                - master
                - dev